import type { Metadata } from "next";
import { Audiowide, Rubik_Lines } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import { ThemeProvider } from "next-themes";

// Fonts
const rubikPixelsFont = Rubik_Lines({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-rubik-lines",
});

const audiowideFont = Audiowide({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-audiowide",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${audiowideFont.variable} ${rubikPixelsFont.variable}`}
      suppressHydrationWarning
    >
      <body className="bg-background text-foreground font-base selection:text-background selection:bg-foreground antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <div className="mx-auto flex min-h-screen w-full max-w-4xl flex-col px-6 md:px-12">
            <Header className="my-8" />
            <main className="flex-1">{children}</main>
            <Footer className="bg-background sticky bottom-0 flex h-10 items-center justify-center" />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
