import type { Metadata } from "next";
import { Audiowide, Rubik_80s_Fade, Rubik_Lines } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer/Footer";
import Header from "@/components/header/Header";
import { ThemeProvider } from "next-themes";
import Background from "@/components/common/Background";

// Fonts
const rubikPixelsFont = Rubik_Lines({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-rubik-lines",
});

const audiowideFont = Audiowide({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-audiowide",
});

const voidHeaderFont = Rubik_80s_Fade({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-rubik-fade",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${audiowideFont.variable} ${rubikPixelsFont.variable} ${voidHeaderFont.variable}`}
      suppressHydrationWarning
    >
      <body className="text-foreground font-base selection:text-background selection:bg-foreground antialiased">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Background />
          <div className="bg-background mx-auto my-6 flex min-h-screen w-full max-w-4xl flex-col rounded-md px-6 md:px-12">
            <Header className="my-8" />
            <main className="mt-10 flex-1">{children}</main>
            <Footer />
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
